apiVersion: v1
kind: Service
metadata:
  annotations:
    tailscale.com/hostname: zot-ihwa
  labels:
    app.kubernetes.io/name: zot
  name: zot
  namespace: zot
spec:
  loadBalancerClass: tailscale
  ports:
  - name: http
    port: 80
    targetPort: http
  selector:
    app.kubernetes.io/name: zot
  type: LoadBalancer
