apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpa-admission-controller
  namespace: vertical-pod-autoscaler
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: vpa-admission-controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vpa-admission-controller
    spec:
      serviceAccountName: vpa-admission-controller
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534 # nobody
      containers:
      - name: admission-controller
        image: registry.k8s.io/autoscaling/vpa-admission-controller:1.0.0
        imagePullPolicy: Always
        command: ["./admission-controller"]
        args:
        - "--client-ca-file=/etc/tls-certs/ca.crt"
        - "--tls-cert-file=/etc/tls-certs/tls.crt"
        - "--tls-private-key=/etc/tls-certs/tls.key"
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        volumeMounts:
        - name: tls-certs
          mountPath: "/etc/tls-certs"
          readOnly: true
        ports:
        - containerPort: 8000
        - name: prometheus
          containerPort: 8944
      volumes:
      - name: tls-certs
        secret:
          secretName: vpa-tls-certs
