apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpa-recommender
  namespace: vertical-pod-autoscaler
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: vpa-recommender
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vpa-recommender
    spec:
      serviceAccountName: vpa-recommender
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534 # nobody
      containers:
      - name: recommender
        image: registry.k8s.io/autoscaling/vpa-recommender:1.0.0
        imagePullPolicy: Always
        ports:
        - name: prometheus
          containerPort: 8942
