apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpa-updater
  namespace: vertical-pod-autoscaler
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: vpa-updater
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vpa-updater
    spec:
      serviceAccountName: vpa-updater
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534 # nobody
      containers:
      - name: updater
        image: registry.k8s.io/autoscaling/vpa-updater:1.0.0
        imagePullPolicy: Always
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        resources:
          limits:
            cpu: 200m
            memory: 1000Mi
          requests:
            cpu: 50m
            memory: 500Mi
        ports:
        - name: prometheus
          containerPort: 8943
