apiVersion: v1
kind: Service
metadata:
  labels:
    app: admission-webhook
    configmanagement.gke.io/arch: csmr
    configmanagement.gke.io/system: "true"
    monitored: "true"
  name: admission-webhook
  namespace: config-management-system
spec:
  ports:
  - name: admission
    port: 443
    targetPort: admission
  selector:
    app: admission-webhook
