apiVersion: v1
kind: Secret
metadata:
  labels:
    app: admission-webhook
    configmanagement.gke.io/arch: csmr
    configmanagement.gke.io/system: "true"
  name: admission-webhook-cert
  namespace: config-management-system
