apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    configmanagement.gke.io/arch: csmr
    configmanagement.gke.io/system: "true"
  name: reconciler-manager
  namespace: config-management-system
