apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: otelcol
  name: otelcol
  namespace: otelcol
spec:
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: otelcol
  strategy:
    rollingUpdate:
      maxSurge: 50%
  template:
    metadata:
      labels:
        app.kubernetes.io/name: otelcol
    spec:
      containers:
      - args:
        - --config=file:/etc/otelcol/config.yaml
        - --feature-gates=telemetry.useOtelForInternalMetrics,telemetry.useOtelWithSDKConfigurationForInternalTelemetry
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /etc/otelcol/gcp-workload-identity.json
        envFrom:
        - secretRef:
            name: otelcol
        image: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:0.91.0
        livenessProbe:
          httpGet:
            path: /
            port: healthcheck
        name: otelcol
        ports:
        - containerPort: 1777
          name: pprof
        - containerPort: 4317
          name: otlp
        - containerPort: 13133
          name: healthcheck
        - containerPort: 55679
          name: zpages
        readinessProbe:
          httpGet:
            path: /
            port: healthcheck
        startupProbe:
          httpGet:
            path: /
            port: healthcheck
        volumeMounts:
        - mountPath: /etc/otelcol
          name: config
        - name: token
          mountPath: "/var/run/service-account"
          readOnly: true
          enableServiceLinks: false
      serviceAccountName: otelcol
      volumes:
      - configMap:
          name: otelcol
        name: config
      - name: token
        projected:
          sources:
          - serviceAccountToken:
              audience: https://iam.googleapis.com/projects/330311169810/locations/global/workloadIdentityPools/kubernetes/providers/ihwa
              expirationSeconds: 3600
              path: token
