apiVersion: v1
data:
  gcp-workload-identity.json: |
    {
      "type": "external_account",
      "audience": "//iam.googleapis.com/projects/330311169810/locations/global/workloadIdentityPools/kubernetes/providers/ihwa-k3s",
      "subject_token_type": "urn:ietf:params:oauth:token-type:jwt",
      "token_url": "https://sts.googleapis.com/v1/token",
      "credential_source": {
        "file": "/var/run/service-account/token",
        "format": {
          "type": "text"
        }
      },
      "service_account_impersonation_url": "https://iamcredentials.googleapis.com/v1/projects/-/serviceAccounts/ihwa-otelcol@com-seankhliao.iam.gserviceaccount.com:generateAccessToken"
    }
  config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
      jaeger:
        protocols:
          grpc:
          thrift_http:

    exporters:
      otlp/lightstep:
        endpoint: ingest.lightstep.com:443
        headers:
          "lightstep-access-token": "${LIGHTSTEP_ACCESS_TOKEN}"

      otlp/honeycomb:
        endpoint: api.honeycomb.io:443
        headers:
          "x-honeycomb-team": "${X_HONEYCOMB_TEAM}"

      googlecloud:
        project: com-seankhliao

    extensions:
      health_check:
      pprof:
      zpages:

    service:
      extensions:
        - health_check
        - pprof
        - zpages

      pipelines:
        metrics:
          receivers:
            - otlp
          exporters:
            - otlp/lightstep

        traces:
          receivers:
            - otlp
            - jaeger
          exporters:
            - otlp/lightstep
            - otlp/honeycomb
            - googlecloud

      telemetry:
        logs:
          level: info
        metrics:
          level: detailed
          address: 0.0.0.0:8888
          readers:
            - periodic:
                interval: 5000
                exporter:
                  otlp:
                    endpoint: 127.0.0.1:4317
                    protocol: grpc/protobuf
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: otelcol
  name: otelcol
  namespace: otelcol
