apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: weechat
  name: weechat
  namespace: weechat
spec:
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: weechat
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: weechat
    spec:
      containers:
      - command:
        - /usr/bin/weechat-headless
        - --dir
        - /weechat-data/config:/weechat-data/data:/weechat-data/cache:/weechat-data/runtime
        - --stdout
        image: docker.io/weechat/weechat
        name: weechat
        ports:
        - containerPort: 7992
          hostPort: 7992
          name: irc
        - containerPort: 7993
          hostPort: 7993
          name: weechat
        volumeMounts:
        - mountPath: /weechat-data
          name: data
        - mountPath: /weechat-secrets
          name: secrets
      enableServiceLinks: false
      initContainers:
      - command:
        - /usr/bin/bash
        - -c
        - |
          mkdir -p /weechat-data/config /weechat-data/data /weechat-data/cache /weechat-data/runtime && \
          cp /weechat-config/* /weechat-data/config/
        image: docker.io/weechat/weechat
        name: copy-config
        volumeMounts:
        - mountPath: /weechat-config
          name: config
        - mountPath: /weechat-data
          name: data
      volumes:
      - configMap:
          name: weechat
        name: config
      - name: data
        persistentVolumeClaim:
          claimName: weechat
      - name: secrets
        secret:
          secretName: weechat
