apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/name: weechat
  name: weechat
  namespace: weechat
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
