apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: sops-secrets-operator
  namespace: sops-secrets-operator
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sops-secrets-operator
