apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: sops-secrets-operator
  name: sops-secrets-operator
  namespace: sops-secrets-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: sops-secrets-operator
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: sops-secrets-operator
      labels:
        app.kubernetes.io/name: sops-secrets-operator
    spec:
      containers:
      - args:
        - -health-probe-bind-address=:8081
        - -leader-elect
        - -requeue-decrypt-after=5
        - -zap-devel=false
        - -zap-encoder=json
        - -zap-log-level=info
        - -zap-stacktrace-level=error
        - -zap-time-encoding=iso8601
        command:
        - /usr/local/bin/manager
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: SOPS_AGE_KEY_FILE
          value: /var/run/secrets/sops-age/key.txt
        image: isindir/sops-secrets-operator:0.11.0
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: sops-secrets-operator
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        volumeMounts:
        - mountPath: /var/run/secrets/sops-age
          name: age
      serviceAccountName: sops-secrets-operator
      volumes:
      - name: age
        secret:
          secretName: sops-age
