apiVersion: v1
kind: Service
metadata:
  annotations:
    tailscale.com/hostname: softserve-ihwa
  labels:
    app.kubernetes.io/name: softserve
  name: softserve
  namespace: softserve
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  ports:
  - name: git-ssh
    port: 22
    targetPort: git-ssh
  - name: git-http
    port: 80
    targetPort: git-http
  selector:
    app.kubernetes.io/name: softserve
