apiVersion: tekton.dev/v1
kind: Task
metadata:
  labels:
    app.kubernetes.io/name: tekton-builds
  name: blogengine
  namespace: tekton-builds
spec:
  description: |
    build and upload a static website to firebase
  displayName: Run blogengine
  stepTemplate:
    env:
    - name: GOOGLE_APPLICATION_CREDENTIALS
      value: /var/run/service-account/gcp-workload-identity.json
    # - name: GOOGLE_PROJECT
    #   value: com-seankhliao
    volumeMounts:
    - name: token
      mountPath: "/var/run/service-account"
      readOnly: true
    workingDir: $(workspaces.module.path)
  steps:
  - image: ghcr.io/seankhliao/blogengine:latest
    name: blogengine
  volumes:
  - name: token
    projected:
      sources:
      - serviceAccountToken:
          audience: https://iam.googleapis.com/projects/330311169810/locations/global/workloadIdentityPools/kubernetes/providers/ihwa
          expirationSeconds: 3600
          path: token
      - configMap:
          name: gcp-workload-identity
  workspaces:
  - name: module
