apiVersion: v1
kind: ConfigMap
metadata:
  name: gcp-workload-identity
  namespace: tekton-builds
data:
  gcp-workload-identity.json: |
    {
      "type": "external_account",
      "audience": "//iam.googleapis.com/projects/330311169810/locations/global/workloadIdentityPools/kubernetes/providers/ihwa",
      "subject_token_type": "urn:ietf:params:oauth:token-type:jwt",
      "token_url": "https://sts.googleapis.com/v1/token",
      "credential_source": {
        "file": "/var/run/service-account/token",
        "format": {
          "type": "text"
        }
      },
      "service_account_impersonation_url": "https://iamcredentials.googleapis.com/v1/projects/-/serviceAccounts/ihwa-tekton-blogengine@com-seankhliao.iam.gserviceaccount.com:generateAccessToken"
    }
