apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    labels:
        app.kubernetes.io/name: tekton-builds
    name: ghcr-publish
    namespace: tekton-builds
spec:
    secretTemplates:
        - name: ghcr-publish
          type: kubernetes.io/dockerconfigjson
          annotations:
            tekton.dev/docker-0: https://ghcr.io
          stringData:
            .dockerconfigjson: ENC[AES256_GCM,data:0sbKgjtNchNNcvr8MCgKHIFS5tqYFe9PLWiszpr3slWL7GPhczHEgXJC3wk3lgst6QX5GFQ5UysPOSZwBC4uqWdu6LALUrP+azyiCt0eAQXM0rydfO5msf/Kp34kvEROT/KFfABCF0LWO9mOmzTbzHqwtVYWZgXqboFE2QB+Y7trrpZ8ZA+RJD5Ng8YxrygQiv5v,iv:poEAaThy6Iye2Ua/f+e0+sydGvnPfk0PXdR/6AZpsRA=,tag:K2MDRuzQOv1aJAbkOBtq+w==,type:str]
            config.json: ENC[AES256_GCM,data:Rj+ztZFfDcKU+yInSuxukB8UmaD1K77eEMgaNU9E8lyWDUYbry8oaUhBFM2OkPYaMImRU4YYUOC3Hc/QxjTq4qSqHB8+OUMkAiRBhbcRDUtXCeqd8C1Fpplv3RM6mFdJNEDH5fQkmPHq9hEhGdcWRvWxfSiuadDjzCYNWQ5vYGSXvEOLvjU6LnUgLAZvUvGXHI4/,iv:OTa9LUSpGT78X0zh+RgSXk2FXDXFWzxadMqHXrP/2Hk=,tag:XrXPSG9bZpc1O+6Cf+lA1g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14mg08panez45c6lj2cut2l8nqja0k5vm2vxmv5zvc4ufqgptgy2qcjfmuu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhNG82c3BaaDBsamplUmVO
            MjZUTTlRUmZaZ3FKSUZFK2pBYTFPekpRWmdZClpJbjNEbVBiaHlNN3F2ZGJVeDJ0
            dGNKaE9EOFppRnk0MmNkY1Z5VTloUmMKLS0tIHFHbFFUWmFqQXdUM2txMWh2MVFZ
            QmhSUDJ2cDhUamJlSEExUjR6eHdQVHMKJRqI5c0XWNQipEBdceDRo+pdkDIKjb27
            9RdrhXDXDAM7L/BMiWpdFSDZ2DP2YNrr0Y8MI17xew/gM5HlxsTOGA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age19q63k49upkgc03e8rsvm5c04x09vqvp2g5u2x6fjjap5awvq0u6q25z8xp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByN3lXTDN5NTFVbjEwMGJW
            c21IcmhiZzNWZ0o2N1lWbk1oZlNNUmlHcVdrClRNa0c5dDR5WUJldzFSMkJWRjRk
            c0dvREZsdklvSWRaV0FsbDZMNWdhN1UKLS0tIGRMcFpRN1ZMa3VMNUFZdk95N1Q2
            cVhrcjZyS0s0bjNnRUsrZ3NWOW5jajgKvQiYKoOBXOft3ryvIQVg3bINj8kwO9Qg
            gdHBR6p6HfV++t37srvobh/fhFqbLRyHx2CqkTppOZSccl16PUGlWA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-26T19:37:39Z"
    mac: ENC[AES256_GCM,data:3xr0kZ8/cyptW9IEKsG0IMJ66Qzt+Hp9aBVl3KcKSYL9SpW7rlNJujpzYftt0WV2RJXRfzXywX8CTQBXPhjQEuw9N6LmAa+yh1F+8dABWlRhOaLqSuaWT72t3WMuvRBzblhAo+86n/IBFdfedYBNFG0oVeu9fB0uTg0Z4v1xG5M=,iv:bfqoQGKyFj3lXIi8awbQew4gMeMdIZIkNLAMFN3cOnA=,tag:2pU+gUV3pSCbSEq4wQkJDw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)
    version: 3.8.0
