apiVersion: tekton.dev/v1
kind: Task
metadata:
  labels:
    app.kubernetes.io/name: tekton-builds
  name: kaniko
  namespace: tekton-builds
spec:
  description: This Task builds a simple Dockerfile with kaniko and pushes to a registry. This Task stores the image name and digest as results, allowing Tekton Chains to pick up that an image was built & sign it.
  params:
  - description: Name (reference) of the image to build.
    name: IMAGE
  - default: ./Dockerfile
    description: Path to the Dockerfile to build.
    name: DOCKERFILE
  - default: ./
    description: The build context used by Kaniko.
    name: CONTEXT
  - default: []
    name: EXTRA_ARGS
    type: array
  - default: gcr.io/kaniko-project/executor:v1.16.0
    name: BUILDER_IMAGE
  results:
  - description: Digest of the image just built.
    name: IMAGE_DIGEST
  steps:
  - args:
    - $(params.EXTRA_ARGS)
    - --dockerfile=$(params.DOCKERFILE)
    - --context=$(workspaces.source.path)/$(params.CONTEXT)
    - --destination=$(params.IMAGE)
    - --digest-file=$(results.IMAGE_DIGEST.path)
    image: $(params.BUILDER_IMAGE)
    name: build-and-push
    securityContext:
      runAsUser: 0
    workingDir: $(workspaces.source.path)
  workspaces:
  - description: Holds the context and Dockerfile
    name: source
  - description: Includes a docker `config.json`
    mountPath: /kaniko/.docker
    name: dockerconfig
    optional: true
