apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    labels:
        app.kubernetes.io/name: tekton-builds
    name: softserve-clone
    namespace: tekton-builds
spec:
    secretTemplates:
        - name: operator-oauth
          annotations:
            tekton.dev/git-0: softserve.softserve.svc
          type: kubernetes.io/ssh-auth
          stringData:
            ssh-privatekey: ENC[AES256_GCM,data:OEd3mN12bKmpuij6r6eyEZfuVRpRx7r3dFw4Pp+4JcSv2nKTi/OeEx7quZ5AK4rlMroETfBbUIlb+r1Bk6TZVze7oy+Eqg6I6I+qlY1S8FWXvB8jF022oVxb96JWVNxHyPq7qiSlofdq53BMjgxGdAf/HkkLfcj/uFRksgOpjD4W1b/kMKSCVa17Uct0Hr+hhyalUTdMcqtyUtp8hLau4vmr7+tHguY59x3Xw6QU7jLx4lt2lkBXO2MlydBrBGCJocpbBhaWDDBYPQxGOkTU93ERDqpA/R/UWB3DEBapRpPRGcy1EWw3XdSeO8kk7PEkMoHCsuIiEs3WAUcrEIXVh/kWzv1RimUz5OQGh3JW3MD7w74jgDA1GTUCKXM44XtFqJbtfHQhW2KbTTl8aQeap4t1FkiT47I3OuYnGNSN+YxgYXWeVgmNRtC8ku/D6V8qp8l2BhB49w4MfZdFJ0vOSvNADDW7VJ3tTp690CLQeKrsmM+WRDktbRV0MWsDsWI43ZgimwnPPk0aB2RQGAd+,iv:KlNdXg4eyRkcN0na7IL0h7v51dz5xxsesCyvk3Im/4U=,tag:1KThipAws0hoafxWYoakoA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14mg08panez45c6lj2cut2l8nqja0k5vm2vxmv5zvc4ufqgptgy2qcjfmuu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrc0ZlbHJ4RXk1QWFxZ0Vy
            S2lkMUxCdk8zVkcvQlArdVdzZWRERlZTbGlrCnBlcEZZYUdvMTk0bkM1a1Nzclpx
            YXp6akZ4SWtxRS9jZzEzbG1vcHppaEkKLS0tIHZ1cFFyNlFocXBwNjdhLzFBVStx
            RUhLcjFEV0laSkNPVStBZzdTMlNQSHMK3CUyAg32lmBgHs7+iye0eDCuNQbMPF8s
            gdyrhW3ZzJVImr6GwQ7/QCYiTJ/APg1Vuq1hnYCZ87bssCzB9hII2A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age19q63k49upkgc03e8rsvm5c04x09vqvp2g5u2x6fjjap5awvq0u6q25z8xp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5WmtZLy9vTTdOczNTYnNE
            Q2tyS2RaQWhlbXRFT21ETStQTUd5T2o3eGtVCkJRUjltM1UxbDhTTDBQM2I3bm0w
            NHYxSjZLdGRJd1pOREh2Q3R1L2ZUS2sKLS0tIGlIc3U1a2dMVWFVcXIwZDhmbWVh
            bWowV2ZUNW1YbFlaVkNrTFY1eGg5UXMKV6mP+tcPLuR8WThZes9FD/mNOMk9QBVB
            qpFl4cDkBIk6wIHRR3BR+4iuCOpFsPz2Hc7T5Lumu+RBXfKFSPp2bA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-26T19:37:31Z"
    mac: ENC[AES256_GCM,data:fp976CqMx5MqvIcrel+DiGLW9ZJNfaZ/2/inL071XFHKxHLoY56K6x+8nuD6wCQRFfmVi5cxuXqaQNbugXOWGaIBUOguhqmZvmILo8Qw04ov0Zq2J2g7UhaVQ2heCLbveJQ509a7UA+jTvHUlv3souZc8YJ7h1rVBktJ7FfSIUQ=,iv:ZLhISl0C2t+ufbNJvsvo6gAprecJ4HP+gx97eTbO3Ro=,tag:dBHcmWZpw6s+xgarJffhHw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)
    version: 3.8.0
