kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tekton-pipelinerun-cleaner
  namespace: tekton-builds
rules:
- apiGroups:
  - tekton.dev
  resources:
  - pipelineruns
  verbs:
  - delete
  - get
  - watch
  - list
