apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/name: bazelremote
  name: bazelremote
  namespace: bazelremote
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 41Gi
