apiVersion: v1
kind: Service
metadata:
  annotations:
    tailscale.com/hostname: bazelremote-ihwa
  labels:
    app.kubernetes.io/name: bazelremote
  name: bazelremote
  namespace: bazelremote
spec:
  loadBalancerClass: tailscale
  ports:
  - appProtocol: HTTP
    name: http
    port: 8080
    targetPort: http
  - appProtocol: GRPC
    name: grpc
    port: 9092
    targetPort: grpc
  selector:
    app.kubernetes.io/name: bazelremote
  type: LoadBalancer
