apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: tailscale
  name: operator
  namespace: tailscale
spec:
  replicas: 1
  selector:
    matchLabels:
      app: operator
      app.kubernetes.io/name: tailscale
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: operator
        app.kubernetes.io/name: tailscale
    spec:
      containers:
      - env:
        - name: OPERATOR_HOSTNAME
          value: tailscale-operator
        - name: OPERATOR_SECRET
          value: operator
        - name: OPERATOR_LOGGING
          value: info
        - name: OPERATOR_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CLIENT_ID_FILE
          value: /oauth/client_id
        - name: CLIENT_SECRET_FILE
          value: /oauth/client_secret
        - name: PROXY_IMAGE
          value: tailscale/tailscale:unstable
        - name: PROXY_TAGS
          value: tag:k8s
        - name: AUTH_PROXY
          value: "false"
        image: tailscale/k8s-operator:unstable
        name: operator
        resources:
          requests:
            cpu: 500m
            memory: 100Mi
        volumeMounts:
        - mountPath: /oauth
          name: oauth
          readOnly: true
      serviceAccountName: operator
      volumes:
      - name: oauth
        secret:
          secretName: operator-oauth
