apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/name: tailscale
  name: proxies
  namespace: tailscale
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - '*'
