apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: gateway-api
    name: gateway-api-webhook-server
  name: gateway-api-admission-server
  namespace: gateway-system
spec:
  ports:
  - name: https-webhook
    port: 443
    targetPort: 8443
  selector:
    app.kubernetes.io/name: gateway-api
    name: gateway-api-admission-server
  type: ClusterIP
