apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app.kubernetes.io/name: gateway-api
    name: gateway-api-webhook
  name: gateway-api-admission
  namespace: gateway-system
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: gateway-api
        name: gateway-api-webhook
      name: gateway-api-admission-create
    spec:
      containers:
      - args:
        - create
        - --host=gateway-api-admission-server,gateway-api-admission-server.gateway-system.svc
        - --namespace=gateway-system
        - --secret-name=gateway-api-admission
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: registry.k8s.io/ingress-nginx/kube-webhook-certgen:v1.1.1
        imagePullPolicy: IfNotPresent
        name: create
      restartPolicy: OnFailure
      securityContext:
        runAsNonRoot: true
        runAsUser: 2000
      serviceAccountName: gateway-api-admission
