apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/name: goproxy
  name: goproxy
  namespace: goproxy
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
