apiVersion: v1
kind: Service
metadata:
  annotations:
    tailscale.com/hostname: goproxy-ihwa
  labels:
    app.kubernetes.io/name: goproxy
  name: goproxy
  namespace: goproxy
spec:
  loadBalancerClass: tailscale
  ports:
  - appProtocol: HTTP
    name: http
    port: 80
    targetPort: http
  selector:
    app.kubernetes.io/name: goproxy
  type: LoadBalancer
