apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  labels:
    app: admission-webhook
    configmanagement.gke.io/arch: csmr
    configmanagement.gke.io/system: "true"
  name: admission-webhook.configsync.gke.io
webhooks: []
