# Setup ClusterRoleBinding between ClusterRole and ServiceAccount.
# ClusterRoleBinding is namespace-less and must have unique name
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: clickhouse-operator-clickhouse-operator
  #namespace: clickhouse-operator
  labels:
    clickhouse.altinity.com/chop: 0.22.0
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: clickhouse-operator-clickhouse-operator
subjects:
- kind: ServiceAccount
  name: clickhouse-operator
  namespace: clickhouse-operator
