apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    configmanagement.gke.io/arch: csmr
    configmanagement.gke.io/system: "true"
  name: configsync.gke.io:reconciler-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: reconciler-manager
  namespace: config-management-system
