# Source: alloydbomni-operator/charts/alloydbomni-operator-fleet/templates/crs.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fleet-metrics-reader
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
