apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: gateway-api
    name: gateway-api-webhook
  name: gateway-api-admission
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gateway-api-admission
subjects:
- kind: ServiceAccount
  name: gateway-api-admission
  namespace: gateway-system
