apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: google-production
spec:
  acme:
    email: acme+google@liao.dev
    server: https://dv.acme-v02.api.pki.goog/directory
    privateKeySecretRef:
      name: google-production-account
    externalAccountBinding:
      keyID: 30482f5e11f86f8c67139eabf9ec7056
      keySecretRef:
        name: gcp-publicca-production
        key: b64MacKey
    solvers:
    - dns01:
        cloudDNS:
          project: com-seankhliao
          serviceAccountSecretRef:
            name: gcp-cert-manager-sa
            key: key.json
