# Source: alloydbomni-operator/templates/local-crs.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: local-metrics-reader
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
