# Source: alloydbomni-operator/templates/local-crs.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: local-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: local-proxy-role
subjects:
- kind: ServiceAccount
  name: local-controller-manager
  namespace: alloydb-omni-system
