apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: resource-group-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: resource-group-manager-role
subjects:
- kind: ServiceAccount
  name: resource-group-sa
  namespace: resource-group-system
