apiVersion: triggers.tekton.dev/v1alpha1
kind: ClusterInterceptor
metadata:
  labels:
    app.kubernetes.io/name: tekton-triggers
    server/type: https
  name: slack
spec:
  clientConfig:
    service:
      name: tekton-triggers-core-interceptors
      namespace: tekton-pipelines
      path: slack
      port: 8443
