apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: system:vpa-status-actor
rules:
- apiGroups:
  - "autoscaling.k8s.io"
  resources:
  - verticalpodautoscalers/status
  verbs:
  - get
  - patch
