apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: tailscale
  name: tailscale-operator
rules:
- apiGroups:
  - ""
  resources:
  - services
  - services/status
  verbs:
  - '*'
