apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/instance: default
    app.kubernetes.io/name: tekton-triggers
    app.kubernetes.io/part-of: tekton-triggers
  name: tekton-triggers-core-interceptors-secrets
rules:
- apiGroups:
  - triggers.tekton.dev
  resources:
  - clusterinterceptors
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - ""
  resourceNames:
  - tekton-triggers-core-interceptors-certs
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
  - update
