# Source: alloydbomni-operator/charts/alloydbomni-operator-fleet/templates/crs.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: fleet-leader-election-rolebinding
  namespace: alloydb-omni-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: fleet-leader-election-role
subjects:
- kind: ServiceAccount
  name: fleet-controller-manager
  namespace: alloydb-omni-system
