# Source: alloydbomni-operator/charts/alloydbomni-operator-fleet/templates/webhooks.yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: fleet-serving-cert
  namespace: alloydb-omni-system
spec:
  dnsNames:
  - fleet-webhook-service.alloydb-omni-system.svc
  - fleet-webhook-service.alloydb-omni-system.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: fleet-selfsigned-issuer
  secretName: fleet-webhook-server-cert
