# Source: alloydbomni-operator/templates/local-crs.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: local-leader-election-rolebinding
  namespace: alloydb-omni-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: local-leader-election-role
subjects:
- kind: ServiceAccount
  name: local-controller-manager
  namespace: alloydb-omni-system
