apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/component: interceptors
    app.kubernetes.io/instance: default
    app.kubernetes.io/name: tekton-triggers
    app.kubernetes.io/part-of: tekton-triggers
    triggers.tekton.dev/release: v0.25.0
  name: tekton-triggers-core-interceptors-certs
  namespace: tekton-pipelines
