apiVersion: v1
kind: Service
metadata:
  labels:
    app: tekton-triggers-core-interceptors
    app.kubernetes.io/component: interceptors
    app.kubernetes.io/instance: default
    app.kubernetes.io/name: tekton-triggers
    app.kubernetes.io/part-of: tekton-triggers
    app.kubernetes.io/version: v0.25.0
    triggers.tekton.dev/release: v0.25.0
    version: v0.25.0
  name: tekton-triggers-core-interceptors
  namespace: tekton-pipelines
spec:
  ports:
  - name: https
    port: 8443
  selector:
    app.kubernetes.io/component: interceptors
    app.kubernetes.io/instance: default
    app.kubernetes.io/name: tekton-triggers
    app.kubernetes.io/part-of: tekton-triggers
