apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: interceptors
    app.kubernetes.io/instance: default
    app.kubernetes.io/name: tekton-triggers
    app.kubernetes.io/part-of: tekton-triggers
    app.kubernetes.io/version: v0.25.0
    triggers.tekton.dev/release: v0.25.0
  name: tekton-triggers-core-interceptors
  namespace: tekton-pipelines
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: interceptors
      app.kubernetes.io/instance: default
      app.kubernetes.io/name: tekton-triggers
      app.kubernetes.io/part-of: tekton-triggers
  template:
    metadata:
      labels:
        app: tekton-triggers-core-interceptors
        app.kubernetes.io/component: interceptors
        app.kubernetes.io/instance: default
        app.kubernetes.io/name: tekton-triggers
        app.kubernetes.io/part-of: tekton-triggers
        app.kubernetes.io/version: v0.25.0
        triggers.tekton.dev/release: v0.25.0
        version: v0.25.0
    spec:
      containers:
      - args:
        - -logtostderr
        - -stderrthreshold
        - INFO
        env:
        - name: SYSTEM_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CONFIG_LOGGING_NAME
          value: config-logging-triggers
        - name: CONFIG_OBSERVABILITY_NAME
          value: config-observability-triggers
        - name: METRICS_DOMAIN
          value: tekton.dev/triggers
        - name: INTERCEPTOR_TLS_SVC_NAME
          value: tekton-triggers-core-interceptors
        - name: INTERCEPTOR_TLS_SECRET_NAME
          value: tekton-triggers-core-interceptors-certs
        image: gcr.io/tekton-releases/github.com/tektoncd/triggers/cmd/interceptors:v0.25.0@sha256:62cd1b675e87dfbb66d1428c582e1be2f3f3ba4c073c132c700bfe3f92e8eb8f
        name: tekton-triggers-core-interceptors
        ports:
        - containerPort: 8443
        readinessProbe:
          httpGet:
            path: /ready
            port: 8443
            scheme: HTTPS
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsGroup: 65532
          runAsNonRoot: true
          runAsUser: 65532
          seccompProfile:
            type: RuntimeDefault
      serviceAccountName: tekton-triggers-core-interceptors
