apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/instance: default
    app.kubernetes.io/name: tekton-triggers
    app.kubernetes.io/part-of: tekton-triggers
  name: tekton-triggers-info
  namespace: tekton-pipelines
rules:
- apiGroups:
  - ""
  resourceNames:
  - triggers-info
  resources:
  - configmaps
  verbs:
  - get
