apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: events
    app.kubernetes.io/instance: default
    app.kubernetes.io/name: tekton-pipelines
    app.kubernetes.io/part-of: tekton-pipelines
  name: tekton-events-controller
  namespace: tekton-pipelines
