apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: default
    app.kubernetes.io/name: tekton-triggers
    app.kubernetes.io/part-of: tekton-triggers
  name: tekton-triggers-webhook-admin
  namespace: tekton-pipelines
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tekton-triggers-admin-webhook
subjects:
- kind: ServiceAccount
  name: tekton-triggers-webhook
  namespace: tekton-pipelines
