apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: tekton-triggers-core-interceptors
  namespace: tekton-pipelines
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tekton-triggers-core-interceptors
