apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: eg
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: envoy-gateway
    app.kubernetes.io/version: latest
    control-plane: envoy-gateway
    helm.sh/chart: gateway-helm-v0.0.0-latest
  name: envoy-gateway-metrics-service
  namespace: envoy-gateway-system
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    app.kubernetes.io/instance: eg
    app.kubernetes.io/name: envoy-gateway
    control-plane: envoy-gateway
