apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: envoy-gateway
  namespace: envoy-gateway-system
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: envoy-gateway
