apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    labels:
        app.kubernetes.io/name: tekton-builds
    name: spicedb
    namespace: spicedb
spec:
    secretTemplates:
        - name: spicedb-creds
          stringData:
            preshared_key: ENC[AES256_GCM,data:yeVJ/rP9FAv0Gs/KVsOt3IqWBaKf+Iw+zbUOWvSGYGZIgb/t+i7A3sRTpIrCNschOAH5iIcB5aRjKOZDoPyUXg==,iv:ynmTTH8Q6ucdbx0etsWqZYhbrgkeAtfRCrVPhiIcXNI=,tag:03HwmrkJMVZpF0jf1k6qyQ==,type:str]
            datastore_uri: ENC[AES256_GCM,data:Blqm47FuWq3VxXhArK3E1ylOOazJvCHyKTh+g+J0BytjDeb+xZ0+xED7wAo6l5udF/M4e2miGy5cFaq2aby//5SPHBoEt3B87XVTG6SEt973gDqZp0NyUmVgCQbIls50sskZaNwxNATMGOSs7ysETKQVOBpGevebpcYU9x3uclLxaYDIediZgg==,iv:6dD2wa+vLkgAsnpZX20xRsUNw14Rz8qUZVNEQcPTvAg=,tag:HVEbQsUyX1m9XQfEDQjp/g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14mg08panez45c6lj2cut2l8nqja0k5vm2vxmv5zvc4ufqgptgy2qcjfmuu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLRWFsRU9PTlZ3bloxeXU2
            VjJoVXU4NFNZK25TNEJzUkczSGVVN1FLekVvCmhMbWN6Q3R2Zyt5TDZidjBacHY3
            ZkR2YzVSMUMySHZPOCtNSmo4cm5kRGcKLS0tIEFaMUVhcWQyUEpYZEh2V3JPRFJz
            dWJvZDd4UmJXcllWcVk5R3ZtZmJiWmcK6gfPE/rAiVkCF+JhicLWi7JKktHDP6Rg
            gk+5oP1fIFCPnl+kJAMU+QBlecx1O+9otkZbB6DaV/zwITenEvAlvQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age19q63k49upkgc03e8rsvm5c04x09vqvp2g5u2x6fjjap5awvq0u6q25z8xp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJWFR5ZkFIQzZGT2tNazVS
            dk81TVlaNnhlbElHMTBKNWppUUQ2Mkh6eFY0CkF1RUhLNGtLUy9PclJxQjN4Sm5x
            dEpVNlFnRUVtOXZFaTJKWFlQTlM4bE0KLS0tIDU5SEs3L1BtejBiakwwRUxiV0JK
            RkQveXRoazRXelBERFVpRytFbnBMR2MKzLt/O1PBBVEUegWOgcEfARShlODuc/eU
            V2UQ+TSlhb9d6O3fl86h/R7jIYtzaVQ41sItD7t/surqE68p+w+7JQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-22T10:49:15Z"
    mac: ENC[AES256_GCM,data:TuWtQyLXjjILJk/1FUCudr6qcWToyar/FnxVK1ZMTnmhpgLpXI4vbJO2hxhX/442sbzlYlSf0mVg23/FFbMnv/sQLma8Az4UsJqQeRhXxHFUcc9ciu1rU0YncEseb1p8l4G+zXUjI4J36mozgv6bIyMdSOtWrbzimBrEyFIt324=,iv:mjdGKuivthVz5DTTS4A+O2gnsTuGjVml4NCA+fImgko=,tag:Szcm4AREYM+GtVWW3Q8wwQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)
    version: 3.8.1
