apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    labels:
        app.kubernetes.io/name: tekton-builds
    name: spicedb
    namespace: spicedb
spec:
    secretTemplates:
        - name: spicedb-creds
          stringData:
            preshared_key: ENC[AES256_GCM,data:GYPVGgBCYVQcRWmtYKhXQy70Pk/dxLWJoC8+y/k/Ydz1tIJAVwuy5fUwZ8arXQL7Pg58ZVmZPTP1mRG47QSHF60Cvg==,iv:2G75Yo4raN01BzzwDsDAJsCuGUnFLKfKoiYL2NzQNHs=,tag:v+dpwlle2/NRP/SfVZL1+w==,type:str]
            datastore_uri: ENC[AES256_GCM,data:Tz0zRLtQ8i3QTJw9j6sYp9x/lGqsJDdxTp+RpWWMarqWClAv2JefPkRNwHj3jwfyDxgZfgK9A4f7FWWn99nC82laaMQU7Ys2,iv:23JIA9Tl7kAOaMHArVRes/yDqd4vdUNYejrYLGKV6R0=,tag:T0gVir0OTS0vQ4mi5fVnFQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14mg08panez45c6lj2cut2l8nqja0k5vm2vxmv5zvc4ufqgptgy2qcjfmuu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLRWFsRU9PTlZ3bloxeXU2
            VjJoVXU4NFNZK25TNEJzUkczSGVVN1FLekVvCmhMbWN6Q3R2Zyt5TDZidjBacHY3
            ZkR2YzVSMUMySHZPOCtNSmo4cm5kRGcKLS0tIEFaMUVhcWQyUEpYZEh2V3JPRFJz
            dWJvZDd4UmJXcllWcVk5R3ZtZmJiWmcK6gfPE/rAiVkCF+JhicLWi7JKktHDP6Rg
            gk+5oP1fIFCPnl+kJAMU+QBlecx1O+9otkZbB6DaV/zwITenEvAlvQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age19q63k49upkgc03e8rsvm5c04x09vqvp2g5u2x6fjjap5awvq0u6q25z8xp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJWFR5ZkFIQzZGT2tNazVS
            dk81TVlaNnhlbElHMTBKNWppUUQ2Mkh6eFY0CkF1RUhLNGtLUy9PclJxQjN4Sm5x
            dEpVNlFnRUVtOXZFaTJKWFlQTlM4bE0KLS0tIDU5SEs3L1BtejBiakwwRUxiV0JK
            RkQveXRoazRXelBERFVpRytFbnBMR2MKzLt/O1PBBVEUegWOgcEfARShlODuc/eU
            V2UQ+TSlhb9d6O3fl86h/R7jIYtzaVQ41sItD7t/surqE68p+w+7JQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-23T12:10:13Z"
    mac: ENC[AES256_GCM,data:2vPy2W+gGFPHLEoNOgz5XVPJGJUsZBD/yXwN3kgLXYSUSf3fqkOaze7wZhXuSHTaChp8COrqtp/gDdkOAKBHWf/FWS5/o1I20WxqzArhaZ4WIb/2BpaIDydp8ymiFG0R3LMQHY+ThzWShm/+8Lis5ZYxN0XfbGgoUE+xMf9nS9Y=,iv:+bVoHQd4in+qKveKf/1L8BUi++QwJfFsjDzEgp71SX8=,tag:hcQbsfQewtWFZPUwyWJNAQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)
    version: 3.8.1
