apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: spicedb-operator
    app.kubernetes.io/instance: spicedb-operator
  name: spicedb-operator
  namespace: spicedb-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spicedb-operator
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: spicedb-operator
        app.kubernetes.io/instance: spicedb-operator
    spec:
      containers:
      - args:
        - run
        - -v=4
        - --crd=false
        - --config
        - /opt/operator/config.yaml
        image: ghcr.io/authzed/spicedb-operator:latest
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 15
        name: spicedb-operator
        ports:
        - containerPort: 8080
          name: prometheus
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          periodSeconds: 1
          successThreshold: 1
          timeoutSeconds: 15
        resources:
          limits:
            cpu: 250m
            memory: 128Mi
          requests:
            cpu: 20m
            memory: 32Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsGroup: 65532
          runAsNonRoot: true
          runAsUser: 65532
          seccompProfile:
            type: RuntimeDefault
        terminationMessagePolicy: FallbackToLogsOnError
      securityContext:
        runAsGroup: 65532
        runAsNonRoot: true
        runAsUser: 65532
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: spicedb-operator
