# Template Parameters:
#
# COMMENT=
# NAMESPACE=clickhouse-operator
# NAME=clickhouse-operator
#
# Setup ServiceAccount
apiVersion: v1
kind: ServiceAccount
metadata:
  name: clickhouse-operator
  namespace: clickhouse-operator
  labels:
    clickhouse.altinity.com/chop: 0.22.0
