apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: clickhouses
  namespace: clickhouse-operator
spec:
  defaults:
    templates:
      dataVolumeClaimTemplate: data-volume-template
      serviceTemplate: service-template
  configuration:
    users:
      user/password: f93cfeb6fe575ebe
      user/profile: default
      user/quota: default
      user/grants:
        - GRANT SHOW ON *.*
        - GRANT SELECT ON system.*
      user/networks/ip:
        - 10.0.0.0/8
    clusters:
    - name: "test1"
      layout:
        shardsCount: 1
        replicasCount: 1
  templates:
    serviceTemplates:
      - name: service-template
        spec:
          ports:
            - name: http
              port: 8123
            - name: client
              port: 9000
          type: ClusterIP
    volumeClaimTemplates:
    - name: data-volume-template
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi
