apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: clickhouse-operator
  namespace: clickhouse-operator
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: clickhouse-operator
