apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: clickhouses
  namespace: clickhouse-operator
spec:
  defaults:
    templates:
      dataVolumeClaimTemplate: data-volume-template
  configuration:
    users:
      user/password: user
      user/profile: default
      user/quota: default
    clusters:
    - name: "goproxyindex"
      layout:
        shardsCount: 1
        replicasCount: 1
  templates:
    volumeClaimTemplates:
    - name: data-volume-template
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
