apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    configmanagement.gke.io/arch: csmr
    configmanagement.gke.io/system: "true"
    control-plane: controller-manager
  name: resource-group-controller-manager
  namespace: resource-group-system
spec:
  replicas: 1
  selector:
    matchLabels:
      configmanagement.gke.io/arch: csmr
      configsync.gke.io/deployment-name: resource-group-controller-manager
      control-plane: controller-manager
  template:
    metadata:
      labels:
        configmanagement.gke.io/arch: csmr
        configsync.gke.io/deployment-name: resource-group-controller-manager
        control-plane: controller-manager
    spec:
      containers:
      - args:
        - --metrics-addr=127.0.0.1:8080
        - --enable-leader-election
        command:
        - /manager
        env:
        - name: OC_RESOURCE_LABELS
          value: k8s.container.name="manager"
        image: ghcr.io/seankhliao/kpt-config-sync-resource-group-controller
        name: manager
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
      serviceAccountName: resource-group-sa
      terminationGracePeriodSeconds: 10
